### ISSUE TITLE
TypeError: Invalid value "undefined" for header "Content-Length"

### ISSUE THREAD

**Issue by SOG-web** [EddyVerbruggen/remove.bg#10]
I get this error when trying to use this package
```
TypeError: Invalid value "undefined" for header "Content-Length"
    at ClientRequest.setHeader (node:_http_outgoing:579:3)
    at FormData.<anonymous> (C:\Users\Olalekan\Documents\GitHub\Seedvendue-server\node_modules\unirest\node_modules\form-data\lib\form_data.js:321:13)
    at C:\Users\Olalekan\Documents\GitHub\Seedvendue-server\node_modules\unirest\node_modules\form-data\lib\form_data.js:265:7
    at C:\Users\Olalekan\Documents\GitHub\Seedvendue-server\node_modules\async\lib\async.js:251:17
    at done (C:\Users\Olalekan\Documents\GitHub\Seedvendue-server\node_modules\async\lib\async.js:126:15)
    at C:\Users\Olalekan\Documents\GitHub\Seedvendue-server\node_modules\async\lib\async.js:32:16
    at C:\Users\Olalekan\Documents\GitHub\Seedvendue-server\node_modules\async\lib\async.js:248:21
    at C:\Users\Olalekan\Documents\GitHub\Seedvendue-server\node_modules\async\lib\async.js:572:34
    at C:\Users\Olalekan\Documents\GitHub\Seedvendue-server\node_modules\unirest\node_modules\form-data\lib\form_data.js:105:13
    at FSReqCallback.oncomplete (node:fs:198:21)
```

``` js
images.forEach(async (image) => {
        const bgRemove = await this.bgRemover.RemoveBgFunction(
          `./upload/products/${image.filename}`,
          `./upload/products/${image.filename}`,
        );
```

``` ts
export class BgRemover {
  constructor(private readonly config: ConfigService) {}

  async RemoveBgFunction(
    path: string,
    outputFile: string,
  ): Promise<object> | null {
    try {
      const result: RemoveBgResult = await removeBackgroundFromImageFile({
        path,
        apiKey: this.config.get('BG_REMOVER_API'),
        size: 'regular',
        crop: false,
        scale: '50%',
        outputFile,
      });

      return { result: result, status: true };
    } catch (error) {
      console.log(error);
      return null;
    }
  }
}
```

**Comment by SOG-web** [comment]
Am using NestJs

**Comment by SOG-web** [comment]
Thanks so much, it works now. I just had to give a correct path for it to work
